import {JSDOM, VirtualConsole} from 'jsdom';
import {readFileSync,readdirSync,existsSync} from 'node:fs';
import assert from 'node:assert/strict';
const js=readFileSync('dist/assets/'+readdirSync('dist/assets').find(x=>x.endsWith('.js')),'utf8');
const pause=()=>new Promise(r=>setTimeout(r,35));
const errors=[];let checks=0;
function check(v,m){assert.ok(v,m);checks++}
async function open(path){const vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e.message));const dom=new JSDOM('<html><body><div id="root"></div></body></html>',{url:'https://demo.example'+path,runScripts:'outside-only',pretendToBeVisual:true,virtualConsole:vc});dom.window.scrollTo=()=>{};dom.window.eval(js);await pause();return dom;}
const home=await open('/');check(home.window.document.querySelector('h1').textContent.includes('Better decisions'),'Home hero');
const paths=new Set(['/','/about','/services','/industries','/courses','/work','/contact']);
const catalog=await open('/services');for(const a of catalog.window.document.querySelectorAll('.service-card'))paths.add(new URL(a.href).pathname);catalog.window.close();
for(const path of paths){const dom=await open(path);const doc=dom.window.document;check(doc.querySelector('h1')&& !doc.body.textContent.includes('A little off the map'),path+' renders');check(doc.querySelectorAll('main').length===1,path+' landmark');for(const img of doc.querySelectorAll('img')){check(!!img.alt,path+' image alt');check(existsSync('public'+new URL(img.src).pathname),path+' local image exists');}dom.window.close();}
const doc=home.window.document;
doc.querySelector('.mobile-toggle').click();await pause();check(doc.querySelector('.mobile-toggle').getAttribute('aria-expanded')==='true','Mobile menu opens');doc.querySelector('nav a[href="/about"]').click();await pause();check(home.window.location.pathname==='/about','Navigation works');check(doc.querySelector('.mobile-toggle').getAttribute('aria-expanded')==='false','Navigation closes menu');home.window.close();
const work=await open('/work');const w=work.window;for(const b of w.document.querySelectorAll('.layer-buttons button')){b.click();await pause();check(b.getAttribute('aria-pressed')==='true','Layer selection '+b.textContent)}w.document.querySelector('[aria-label="Zoom in"]').click();await pause();check(w.document.querySelector('.map-inner').style.transform!=='scale(1)','Zoom changes');w.document.querySelector('.map-pin').click();await pause();check(!!w.document.querySelector('.map-popup'),'Marker opens detail');w.document.querySelector('[aria-label="Close map detail"]').click();await pause();check(!w.document.querySelector('.map-popup'),'Marker closes');
const slider=w.document.querySelector('#comparison');Object.getOwnPropertyDescriptor(w.HTMLInputElement.prototype,'value').set.call(slider,'75');slider.dispatchEvent(new w.Event('input',{bubbles:true}));slider.dispatchEvent(new w.Event('change',{bubbles:true}));await pause();check(w.document.querySelector('.compare-divider').style.left==='75%','Comparison changes');work.window.close();
const contact=await open('/contact?interest=Basic%20course');const c=contact.window;check(c.document.querySelector('#interest').value==='Basic course','Course preselection');let form=c.document.querySelector('form');form.dispatchEvent(new c.Event('submit',{bubbles:true,cancelable:true}));await pause();check(c.document.querySelectorAll('.error').length===5,'Invalid form has errors');for(const [id,value] of Object.entries({name:'Demo Visitor',email:'visitor@example.com',phone:'+91 9999999999',message:'I would like to discuss GIS mapping.'}))c.document.getElementById(id).value=value;c.document.querySelector('#consent').checked=true;form.dispatchEvent(new c.Event('submit',{bubbles:true,cancelable:true}));await pause();check(c.document.body.textContent.includes('Nothing was sent or saved'),'Honest demo confirmation');check(!c.document.querySelector('form'),'Success state');c.document.querySelector('.confirmation button').click();await pause();check(!!c.document.querySelector('form'),'Reset form');contact.window.close();
const missing=await open('/not-a-page');check(missing.window.document.body.textContent.includes('A little off the map'),'404');missing.window.close();
check(errors.length===0,'No runtime DOM errors: '+errors.join('; '));
console.log(`PASS: ${checks} checks across ${paths.size} pages, navigation, map, comparison and form states.`);
