export const services = [
 {slug:'gis-data-mapping',title:'GIS Data Mapping',tag:'Spatial intelligence',intro:'Bring complex location data into focus.',description:'Custom maps and spatial analysis reveal patterns across places, infrastructure and natural resources.',items:['Spatial analysis','Thematic maps','Custom data overlays'],use:'Planning, environmental monitoring and location intelligence'},
 {slug:'digitization',title:'Digitization & Georeferencing',tag:'Connected datasets',intro:'Turn existing records into usable spatial data.',description:'Convert maps and imagery into digital GIS layers aligned to geographic coordinates.',items:['Map digitization','Attribute capture','Georeferenced imagery'],use:'Land records, utilities and infrastructure'},
 {slug:'drone-data-processing',title:'Drone Data Processing',tag:'An aerial perspective',intro:'From aerial imagery to a clearer view of your site.',description:'Process overlapping drone imagery into orthomosaics and terrain information for project planning.',items:['Orthomosaics','DTM, DSM and DEM','Contours and 3D imagery'],use:'Construction, agriculture, mining and land development'},
 {slug:'surveying',title:'Surveying & Data Capture',tag:'Grounded in the field',intro:'Capture the detail that matters on the ground.',description:'DGPS, GPS and Total Station surveying support land measurement and field data collection.',items:['DGPS surveying','GPS data capture','Total Station surveys'],use:'Land surveying and construction layouts'},
 {slug:'cadastral-mapping',title:'Cadastral Mapping',tag:'Land & ownership',intro:'Make land records easier to understand.',description:'Organize property boundaries and associated land information into spatial records.',items:['Survey and khata numbers','Ownership attributes','Land-use and boundary records'],use:'Public land records and property planning'},
 {slug:'topographical-mapping',title:'Topographical Mapping',tag:'Terrain & features',intro:'Understand the shape of a place.',description:'Map terrain alongside natural and built features to inform geographic planning.',items:['Relief and vegetation','Water bodies and settlements','Transport networks'],use:'Civil engineering and route planning'},
 {slug:'agricultural-mapping',title:'Agricultural Mapping',tag:'Land & crops',intro:'See agricultural land in context.',description:'Use GIS and satellite imagery to organize information on crops, soil and vegetation.',items:['Farmland mapping','Crop monitoring inputs','Vegetation interpretation'],use:'Agricultural planning and field management'},
 {slug:'watershed-analysis',title:'Watershed Analysis',tag:'Water & environment',intro:'Follow the movement of water.',description:'Analyze elevation data to identify catchments, streams and drainage networks.',items:['Watershed delineation','Stream networks','Catchment mapping'],use:'Water resource and environmental management'},
 {slug:'image-mosaicking',title:'Image Mosaicking',tag:'A continuous picture',intro:'Connect overlapping imagery.',description:'Combine raster images into a continuous view for mapping and interpretation.',items:['Raster mosaics','Overlapping image integration','Image preparation'],use:'Geographic basemaps and image analysis'},
 {slug:'data-conversion',title:'GIS Data Conversion',tag:'Interoperable data',intro:'Make your geographic data work together.',description:'Convert raster and vector information into formats suited to your GIS workflow.',items:['Vector-to-vector conversion','Raster conversion','Raster and vector interchange'],use:'Data migration and GIS integration'},
 {slug:'data-models',title:'GIS Data Models',tag:'Structured geography',intro:'Organize the world into useful layers.',description:'Represent geographic information through raster and vector models.',items:['Point, line and polygon structures','Raster data models','Spatial data organization'],use:'GIS data management and analysis'},
 {slug:'satellite-image-processing',title:'Satellite Image Processing',tag:'The bigger picture',intro:'Find meaningful detail in satellite imagery.',description:'Prepare and interpret imagery to support land-use and natural resource mapping.',items:['Image processing','Image interpretation','Geographic dataset updates'],use:'Land use, forestry and resource planning'},
 {slug:'change-detection',title:'Change Detection',tag:'Change over time',intro:'Understand what has changed, and where.',description:'Compare imagery from different periods to identify changes in land and infrastructure.',items:['Multi-date image comparison','Change interpretation','Thematic change maps'],use:'Environmental monitoring and urban planning'},
 {slug:'slope-aspect',title:'Slope & Aspect Analysis',tag:'Terrain intelligence',intro:'Read the contours of the landscape.',description:'Derive terrain steepness and orientation from digital elevation models.',items:['Slope analysis','Aspect mapping','Terrain visualization'],use:'Terrain assessment and environmental planning'},
 {slug:'3d-modeling',title:'3D Modeling',tag:'Another dimension',intro:'Explore places beyond a flat map.',description:'Develop three-dimensional representations from drone, aerial or satellite stereo data.',items:['Surface models','Building representations','Textured visualization where data permits'],use:'Architecture and urban planning'},
 {slug:'lidar-processing',title:'LiDAR Data Processing',tag:'Geospatial processing',intro:'Explore your LiDAR processing requirements.',description:'LiDAR data processing is listed among R-Geo Solution’s additional services. Contact the team to confirm scope and available outputs.',items:['Discuss source data','Define required outputs','Confirm processing scope'],use:'Project-specific geospatial requirements'}
];
export const courses=[
 {name:'Basic',duration:'3 months',subtitle:'Start with the foundations.',items:['GIS fundamentals','QGIS & ArcGIS basics','Mapping & visualization','Google Earth & field data','Mini project','Resume & interview preparation']},
 {name:'Advanced',duration:'6 months',subtitle:'Build your analytical toolkit.',items:['Advanced GIS analysis','Remote sensing','CAD integration','Industry project work','Mock interviews','Placement training & job support']},
 {name:'PG Diploma',duration:'12 months',subtitle:'Explore a broader geospatial practice.',items:['GIS & remote sensing','GIS programming with Python','Photogrammetry & drone mapping','Web GIS & server','Final project','Interview preparation & soft skills']}
];
export const industries=[{name:'Urban & Infrastructure',text:'Connect land use, transport and built assets to support planning.',service:'topographical-mapping'}, {name:'Agriculture',text:'Bring field boundaries, crops and vegetation into one spatial view.',service:'agricultural-mapping'}, {name:'Environment & Water',text:'Explore catchments, natural resources and environmental change.',service:'watershed-analysis'}, {name:'Land & Property',text:'Organize parcel boundaries and property information.',service:'cadastral-mapping'}, {name:'Mining & Energy',text:'Use terrain and aerial data to understand sites and infrastructure.',service:'drone-data-processing'}, {name:'Disaster Planning',text:'Use geographic context to support preparedness and change assessment.',service:'change-detection'}];
export const address='02, ABC Nirman Building, Thergaon, Pimpri-Chinchwad, Pune, Maharashtra 411033';
export const originalImages={mapping:'/mapping.webp',drone:'/drone.webp',additional:'https://rgeosolution.com/wp-content/uploads/2024/01/Untitled-design-53.png'};
